#gcloud config set project "project-id"
bq load --source_format=CSV --replace --skip_leading_rows=1 --autodetect raw_zone2.Address gs://bk_sqlserver_ahg/tablas/Address.csv
bq load --source_format=CSV --replace --skip_leading_rows=1 --autodetect raw_zone2.AddressType gs://bk_sqlserver_ahg/tablas/AddressType.csv
bq load --source_format=CSV --replace --skip_leading_rows=1 --autodetect raw_zone2.BillOfMaterials gs://bk_sqlserver_ahg/tablas/BillOfMaterials.csv
bq load --source_format=CSV --replace --skip_leading_rows=1 --autodetect raw_zone2.BusinessEntity gs://bk_sqlserver_ahg/tablas/BusinessEntity.csv
bq load --source_format=CSV --replace --skip_leading_rows=1 --autodetect raw_zone2.BusinessEntityAddress gs://bk_sqlserver_ahg/tablas/BusinessEntityAddress.csv
bq load --source_format=CSV --replace --skip_leading_rows=1 --autodetect raw_zone2.BusinessEntityContact gs://bk_sqlserver_ahg/tablas/BusinessEntityContact.csv
bq load --source_format=CSV --replace --skip_leading_rows=1 --autodetect raw_zone2.ContactType gs://bk_sqlserver_ahg/tablas/ContactType.csv
bq load --source_format=CSV --replace --skip_leading_rows=1 --autodetect raw_zone2.CountryRegion gs://bk_sqlserver_ahg/tablas/CountryRegion.csv
bq load --source_format=CSV --replace --skip_leading_rows=1 --autodetect raw_zone2.CountryRegionCurrency gs://bk_sqlserver_ahg/tablas/CountryRegionCurrency.csv
bq load --source_format=CSV --replace --skip_leading_rows=1 --autodetect raw_zone2.CreditCard gs://bk_sqlserver_ahg/tablas/CreditCard.csv
bq load --source_format=CSV --replace --skip_leading_rows=1 --autodetect raw_zone2.Culture gs://bk_sqlserver_ahg/tablas/Culture.csv
bq load --source_format=CSV --replace --skip_leading_rows=1 --autodetect raw_zone2.Currency gs://bk_sqlserver_ahg/tablas/Currency.csv
bq load --source_format=CSV --replace --skip_leading_rows=1 --autodetect raw_zone2.CurrencyRate gs://bk_sqlserver_ahg/tablas/CurrencyRate.csv
bq load --source_format=CSV --replace --skip_leading_rows=1 --autodetect raw_zone2.Customer gs://bk_sqlserver_ahg/tablas/Customer.csv
bq load --source_format=CSV --replace --skip_leading_rows=1 --autodetect raw_zone2.Department gs://bk_sqlserver_ahg/tablas/Department.csv
bq load --source_format=CSV --replace --skip_leading_rows=1 --autodetect raw_zone2.EmailAddress gs://bk_sqlserver_ahg/tablas/EmailAddress.csv
bq load --source_format=CSV --replace --skip_leading_rows=1 --autodetect raw_zone2.Employee gs://bk_sqlserver_ahg/tablas/Employee.csv
bq load --source_format=CSV --replace --skip_leading_rows=1 --autodetect raw_zone2.EmployeeDepartmentHistory gs://bk_sqlserver_ahg/tablas/EmployeeDepartmentHistory.csv
bq load --source_format=CSV --replace --skip_leading_rows=1 --autodetect raw_zone2.EmployeePayHistory gs://bk_sqlserver_ahg/tablas/EmployeePayHistory.csv
bq load --source_format=CSV --replace --skip_leading_rows=1 --autodetect raw_zone2.Illustration gs://bk_sqlserver_ahg/tablas/Illustration.csv
bq load --source_format=CSV --replace --skip_leading_rows=1 --autodetect raw_zone2.JobCandidate gs://bk_sqlserver_ahg/tablas/JobCandidate.csv
bq load --source_format=CSV --replace --skip_leading_rows=1 --autodetect raw_zone2.Location gs://bk_sqlserver_ahg/tablas/Location.csv
bq load --source_format=CSV --replace --skip_leading_rows=1 --autodetect raw_zone2.Password gs://bk_sqlserver_ahg/tablas/Password.csv
bq load --source_format=CSV --replace --skip_leading_rows=1 --autodetect raw_zone2.Person gs://bk_sqlserver_ahg/tablas/Person.csv
bq load --source_format=CSV --replace --skip_leading_rows=1 --autodetect raw_zone2.PersonCreditCard gs://bk_sqlserver_ahg/tablas/PersonCreditCard.csv
bq load --source_format=CSV --replace --skip_leading_rows=1 --autodetect raw_zone2.PersonPhone gs://bk_sqlserver_ahg/tablas/PersonPhone.csv
bq load --source_format=CSV --replace --skip_leading_rows=1 --autodetect raw_zone2.PhoneNumberType gs://bk_sqlserver_ahg/tablas/PhoneNumberType.csv
bq load --source_format=CSV --replace --skip_leading_rows=1 --autodetect raw_zone2.Product gs://bk_sqlserver_ahg/tablas/Product.csv
bq load --source_format=CSV --replace --skip_leading_rows=1 --autodetect raw_zone2.ProductCategory gs://bk_sqlserver_ahg/tablas/ProductCategory.csv
bq load --source_format=CSV --replace --skip_leading_rows=1 --autodetect raw_zone2.ProductCostHistory gs://bk_sqlserver_ahg/tablas/ProductCostHistory.csv
bq load --source_format=CSV --replace --skip_leading_rows=1 --autodetect raw_zone2.ProductDescription gs://bk_sqlserver_ahg/tablas/ProductDescription.csv
bq load --source_format=CSV --replace --skip_leading_rows=1 --autodetect raw_zone2.ProductInventory gs://bk_sqlserver_ahg/tablas/ProductInventory.csv
bq load --source_format=CSV --replace --skip_leading_rows=1 --autodetect raw_zone2.ProductListPriceHistory gs://bk_sqlserver_ahg/tablas/ProductListPriceHistory.csv
bq load --source_format=CSV --replace --skip_leading_rows=1 --autodetect raw_zone2.ProductModel gs://bk_sqlserver_ahg/tablas/ProductModel.csv
bq load --source_format=CSV --replace --skip_leading_rows=1 --autodetect raw_zone2.ProductModelIllustration gs://bk_sqlserver_ahg/tablas/ProductModelIllustration.csv
bq load --source_format=CSV --replace --skip_leading_rows=1 --autodetect raw_zone2.ProductModelProductDescriptionCulture gs://bk_sqlserver_ahg/tablas/ProductModelProductDescriptionCulture.csv
bq load --source_format=CSV --replace --skip_leading_rows=1 --autodetect raw_zone2.ProductPhoto gs://bk_sqlserver_ahg/tablas/ProductPhoto.csv
bq load --source_format=CSV --replace --skip_leading_rows=1 --autodetect raw_zone2.ProductProductPhoto gs://bk_sqlserver_ahg/tablas/ProductProductPhoto.csv
bq load --source_format=CSV --replace --skip_leading_rows=1 --autodetect raw_zone2.ProductReview gs://bk_sqlserver_ahg/tablas/ProductReview.csv
bq load --source_format=CSV --replace --skip_leading_rows=1 --autodetect raw_zone2.ProductSubcategory gs://bk_sqlserver_ahg/tablas/ProductSubcategory.csv
bq load --source_format=CSV --replace --skip_leading_rows=1 --autodetect raw_zone2.ProductVendor gs://bk_sqlserver_ahg/tablas/ProductVendor.csv
bq load --source_format=CSV --replace --skip_leading_rows=1 --autodetect raw_zone2.PurchaseOrderDetail gs://bk_sqlserver_ahg/tablas/PurchaseOrderDetail.csv
bq load --source_format=CSV --replace --skip_leading_rows=1 --autodetect raw_zone2.PurchaseOrderHeader gs://bk_sqlserver_ahg/tablas/PurchaseOrderHeader.csv
bq load --source_format=CSV --replace --skip_leading_rows=1 --autodetect raw_zone2.SalesOrderDetail gs://bk_sqlserver_ahg/tablas/SalesOrderDetail.csv
bq load --source_format=CSV --replace --skip_leading_rows=1 --autodetect raw_zone2.SalesOrderHeader gs://bk_sqlserver_ahg/tablas/SalesOrderHeader.csv
bq load --source_format=CSV --replace --skip_leading_rows=1 --autodetect raw_zone2.SalesOrderHeaderSalesReason gs://bk_sqlserver_ahg/tablas/SalesOrderHeaderSalesReason.csv
bq load --source_format=CSV --replace --skip_leading_rows=1 --autodetect raw_zone2.SalesPerson gs://bk_sqlserver_ahg/tablas/SalesPerson.csv
bq load --source_format=CSV --replace --skip_leading_rows=1 --autodetect raw_zone2.SalesPersonQuotaHistory gs://bk_sqlserver_ahg/tablas/SalesPersonQuotaHistory.csv
bq load --source_format=CSV --replace --skip_leading_rows=1 --autodetect raw_zone2.SalesReason gs://bk_sqlserver_ahg/tablas/SalesReason.csv
bq load --source_format=CSV --replace --skip_leading_rows=1 --autodetect raw_zone2.SalesTaxRate gs://bk_sqlserver_ahg/tablas/SalesTaxRate.csv
bq load --source_format=CSV --replace --skip_leading_rows=1 --autodetect raw_zone2.SalesTerritory gs://bk_sqlserver_ahg/tablas/SalesTerritory.csv
bq load --source_format=CSV --replace --skip_leading_rows=1 --autodetect raw_zone2.SalesTerritoryHistory gs://bk_sqlserver_ahg/tablas/SalesTerritoryHistory.csv
bq load --source_format=CSV --replace --skip_leading_rows=1 --autodetect raw_zone2.ScrapReason gs://bk_sqlserver_ahg/tablas/ScrapReason.csv
bq load --source_format=CSV --replace --skip_leading_rows=1 --autodetect raw_zone2.Shift gs://bk_sqlserver_ahg/tablas/Shift.csv
bq load --source_format=CSV --replace --skip_leading_rows=1 --autodetect raw_zone2.ShipMethod gs://bk_sqlserver_ahg/tablas/ShipMethod.csv
bq load --source_format=CSV --replace --skip_leading_rows=1 --autodetect raw_zone2.ShoppingCartItem gs://bk_sqlserver_ahg/tablas/ShoppingCartItem.csv
bq load --source_format=CSV --replace --skip_leading_rows=1 --autodetect raw_zone2.SpecialOffer gs://bk_sqlserver_ahg/tablas/SpecialOffer.csv
bq load --source_format=CSV --replace --skip_leading_rows=1 --autodetect raw_zone2.SpecialOfferProduct gs://bk_sqlserver_ahg/tablas/SpecialOfferProduct.csv
bq load --source_format=CSV --replace --skip_leading_rows=1 --autodetect raw_zone2.StateProvince gs://bk_sqlserver_ahg/tablas/StateProvince.csv
bq load --source_format=CSV --replace --skip_leading_rows=1 --autodetect raw_zone2.Store gs://bk_sqlserver_ahg/tablas/Store.csv
bq load --source_format=CSV --replace --skip_leading_rows=1 --autodetect raw_zone2.TransactionHistory gs://bk_sqlserver_ahg/tablas/TransactionHistory.csv
bq load --source_format=CSV --replace --skip_leading_rows=1 --autodetect raw_zone2.TransactionHistoryArchive gs://bk_sqlserver_ahg/tablas/TransactionHistoryArchive.csv
bq load --source_format=CSV --replace --skip_leading_rows=1 --autodetect raw_zone2.UnitMeasure gs://bk_sqlserver_ahg/tablas/UnitMeasure.csv
bq load --source_format=CSV --replace --skip_leading_rows=1 --autodetect raw_zone2.Vendor gs://bk_sqlserver_ahg/tablas/Vendor.csv
bq load --source_format=CSV --replace --skip_leading_rows=1 --autodetect raw_zone2.WorkOrder gs://bk_sqlserver_ahg/tablas/WorkOrder.csv
bq load --source_format=CSV --replace --skip_leading_rows=1 --autodetect raw_zone2.WorkOrderRouting gs://bk_sqlserver_ahg/tablas/WorkOrderRouting.csv