bq load --source_format=CSV --replace --skip_leading_rows=1 raw_zone2.Address gs://bk_sqlserver_ahg/tablas/Address.csv schemas/Address.json
bq load --source_format=CSV --replace --skip_leading_rows=1 raw_zone2.AddressType gs://bk_sqlserver_ahg/tablas/AddressType.csv schemas/AddressType.json
bq load --source_format=CSV --replace --skip_leading_rows=1 raw_zone2.BillOfMaterials gs://bk_sqlserver_ahg/tablas/BillOfMaterials.csv schemas/BillOfMaterials.json
bq load --source_format=CSV --replace --skip_leading_rows=1 raw_zone2.BusinessEntity gs://bk_sqlserver_ahg/tablas/BusinessEntity.csv schemas/BusinessEntity.json
bq load --source_format=CSV --replace --skip_leading_rows=1 raw_zone2.BusinessEntityAddress gs://bk_sqlserver_ahg/tablas/BusinessEntityAddress.csv schemas/BusinessEntityAddress.json
bq load --source_format=CSV --replace --skip_leading_rows=1 raw_zone2.BusinessEntityContact gs://bk_sqlserver_ahg/tablas/BusinessEntityContact.csv schemas/BusinessEntityContact.json
bq load --source_format=CSV --replace --skip_leading_rows=1 raw_zone2.ContactType gs://bk_sqlserver_ahg/tablas/ContactType.csv schemas/ContactType.json
bq load --source_format=CSV --replace --skip_leading_rows=1 raw_zone2.CountryRegion gs://bk_sqlserver_ahg/tablas/CountryRegion.csv schemas/CountryRegion.json
bq load --source_format=CSV --replace --skip_leading_rows=1 raw_zone2.CountryRegionCurrency gs://bk_sqlserver_ahg/tablas/CountryRegionCurrency.csv schemas/CountryRegionCurrency.json
bq load --source_format=CSV --replace --skip_leading_rows=1 raw_zone2.CreditCard gs://bk_sqlserver_ahg/tablas/CreditCard.csv schemas/CreditCard.json
bq load --source_format=CSV --replace --skip_leading_rows=1 raw_zone2.Culture gs://bk_sqlserver_ahg/tablas/Culture.csv schemas/Culture.json
bq load --source_format=CSV --replace --skip_leading_rows=1 raw_zone2.Currency gs://bk_sqlserver_ahg/tablas/Currency.csv schemas/Currency.json
bq load --source_format=CSV --replace --skip_leading_rows=1 raw_zone2.CurrencyRate gs://bk_sqlserver_ahg/tablas/CurrencyRate.csv schemas/CurrencyRate.json
bq load --source_format=CSV --replace --skip_leading_rows=1 raw_zone2.Customer gs://bk_sqlserver_ahg/tablas/Customer.csv schemas/Customer.json
bq load --source_format=CSV --replace --skip_leading_rows=1 raw_zone2.Department gs://bk_sqlserver_ahg/tablas/Department.csv schemas/Department.json
bq load --source_format=CSV --replace --skip_leading_rows=1 raw_zone2.EmailAddress gs://bk_sqlserver_ahg/tablas/EmailAddress.csv schemas/EmailAddress.json
bq load --source_format=CSV --replace --skip_leading_rows=1 raw_zone2.Employee gs://bk_sqlserver_ahg/tablas/Employee.csv schemas/Employee.json
bq load --source_format=CSV --replace --skip_leading_rows=1 raw_zone2.EmployeeDepartmentHistory gs://bk_sqlserver_ahg/tablas/EmployeeDepartmentHistory.csv schemas/EmployeeDepartmentHistory.json
bq load --source_format=CSV --replace --skip_leading_rows=1 raw_zone2.EmployeePayHistory gs://bk_sqlserver_ahg/tablas/EmployeePayHistory.csv schemas/EmployeePayHistory.json
bq load --source_format=CSV --replace --skip_leading_rows=1 raw_zone2.Illustration gs://bk_sqlserver_ahg/tablas/Illustration.csv schemas/Illustration.json
bq load --source_format=CSV --replace --skip_leading_rows=1 raw_zone2.JobCandidate gs://bk_sqlserver_ahg/tablas/JobCandidate.csv schemas/JobCandidate.json
bq load --source_format=CSV --replace --skip_leading_rows=1 raw_zone2.Location gs://bk_sqlserver_ahg/tablas/Location.csv schemas/Location.json
bq load --source_format=CSV --replace --skip_leading_rows=1 raw_zone2.Password gs://bk_sqlserver_ahg/tablas/Password.csv schemas/Password.json
bq load --source_format=CSV --replace --skip_leading_rows=1 raw_zone2.Person gs://bk_sqlserver_ahg/tablas/Person.csv schemas/Person.json
bq load --source_format=CSV --replace --skip_leading_rows=1 raw_zone2.PersonCreditCard gs://bk_sqlserver_ahg/tablas/PersonCreditCard.csv schemas/PersonCreditCard.json
bq load --source_format=CSV --replace --skip_leading_rows=1 raw_zone2.PersonPhone gs://bk_sqlserver_ahg/tablas/PersonPhone.csv schemas/PersonPhone.json
bq load --source_format=CSV --replace --skip_leading_rows=1 raw_zone2.PhoneNumberType gs://bk_sqlserver_ahg/tablas/PhoneNumberType.csv schemas/PhoneNumberType.json
bq load --source_format=CSV --replace --skip_leading_rows=1 raw_zone2.Product gs://bk_sqlserver_ahg/tablas/Product.csv schemas/Product.json
bq load --source_format=CSV --replace --skip_leading_rows=1 raw_zone2.ProductCategory gs://bk_sqlserver_ahg/tablas/ProductCategory.csv schemas/ProductCategory.json
bq load --source_format=CSV --replace --skip_leading_rows=1 raw_zone2.ProductCostHistory gs://bk_sqlserver_ahg/tablas/ProductCostHistory.csv schemas/ProductCostHistory.json
bq load --source_format=CSV --replace --skip_leading_rows=1 raw_zone2.ProductDescription gs://bk_sqlserver_ahg/tablas/ProductDescription.csv schemas/ProductDescription.json
bq load --source_format=CSV --replace --skip_leading_rows=1 raw_zone2.ProductInventory gs://bk_sqlserver_ahg/tablas/ProductInventory.csv schemas/ProductInventory.json
bq load --source_format=CSV --replace --skip_leading_rows=1 raw_zone2.ProductListPriceHistory gs://bk_sqlserver_ahg/tablas/ProductListPriceHistory.csv schemas/ProductListPriceHistory.json
bq load --source_format=CSV --replace --skip_leading_rows=1 raw_zone2.ProductModel gs://bk_sqlserver_ahg/tablas/ProductModel.csv schemas/ProductModel.json
bq load --source_format=CSV --replace --skip_leading_rows=1 raw_zone2.ProductModelIllustration gs://bk_sqlserver_ahg/tablas/ProductModelIllustration.csv schemas/ProductModelIllustration.json
bq load --source_format=CSV --replace --skip_leading_rows=1 raw_zone2.ProductModelProductDescriptionCulture gs://bk_sqlserver_ahg/tablas/ProductModelProductDescriptionCulture.csv schemas/ProductModelProductDescriptionCulture.json
bq load --source_format=CSV --replace --skip_leading_rows=1 raw_zone2.ProductPhoto gs://bk_sqlserver_ahg/tablas/ProductPhoto.csv schemas/ProductPhoto.json
bq load --source_format=CSV --replace --skip_leading_rows=1 raw_zone2.ProductProductPhoto gs://bk_sqlserver_ahg/tablas/ProductProductPhoto.csv schemas/ProductProductPhoto.json
bq load --source_format=CSV --replace --skip_leading_rows=1 raw_zone2.ProductReview gs://bk_sqlserver_ahg/tablas/ProductReview.csv schemas/ProductReview.json
bq load --source_format=CSV --replace --skip_leading_rows=1 raw_zone2.ProductSubcategory gs://bk_sqlserver_ahg/tablas/ProductSubcategory.csv schemas/ProductSubcategory.json
bq load --source_format=CSV --replace --skip_leading_rows=1 raw_zone2.ProductVendor gs://bk_sqlserver_ahg/tablas/ProductVendor.csv schemas/ProductVendor.json
bq load --source_format=CSV --replace --skip_leading_rows=1 raw_zone2.PurchaseOrderDetail gs://bk_sqlserver_ahg/tablas/PurchaseOrderDetail.csv schemas/PurchaseOrderDetail.json
bq load --source_format=CSV --replace --skip_leading_rows=1 raw_zone2.PurchaseOrderHeader gs://bk_sqlserver_ahg/tablas/PurchaseOrderHeader.csv schemas/PurchaseOrderHeader.json
bq load --source_format=CSV --replace --skip_leading_rows=1 raw_zone2.SalesOrderDetail gs://bk_sqlserver_ahg/tablas/SalesOrderDetail.csv schemas/SalesOrderDetail.json
bq load --source_format=CSV --replace --skip_leading_rows=1 raw_zone2.SalesOrderHeader gs://bk_sqlserver_ahg/tablas/SalesOrderHeader.csv schemas/SalesOrderHeader.json
bq load --source_format=CSV --replace --skip_leading_rows=1 raw_zone2.SalesOrderHeaderSalesReason gs://bk_sqlserver_ahg/tablas/SalesOrderHeaderSalesReason.csv schemas/SalesOrderHeaderSalesReason.json
bq load --source_format=CSV --replace --skip_leading_rows=1 raw_zone2.SalesPerson gs://bk_sqlserver_ahg/tablas/SalesPerson.csv schemas/SalesPerson.json
bq load --source_format=CSV --replace --skip_leading_rows=1 raw_zone2.SalesPersonQuotaHistory gs://bk_sqlserver_ahg/tablas/SalesPersonQuotaHistory.csv schemas/SalesPersonQuotaHistory.json
bq load --source_format=CSV --replace --skip_leading_rows=1 raw_zone2.SalesReason gs://bk_sqlserver_ahg/tablas/SalesReason.csv schemas/SalesReason.json
bq load --source_format=CSV --replace --skip_leading_rows=1 raw_zone2.SalesTaxRate gs://bk_sqlserver_ahg/tablas/SalesTaxRate.csv schemas/SalesTaxRate.json
bq load --source_format=CSV --replace --skip_leading_rows=1 raw_zone2.SalesTerritory gs://bk_sqlserver_ahg/tablas/SalesTerritory.csv schemas/SalesTerritory.json
bq load --source_format=CSV --replace --skip_leading_rows=1 raw_zone2.SalesTerritoryHistory gs://bk_sqlserver_ahg/tablas/SalesTerritoryHistory.csv schemas/SalesTerritoryHistory.json
bq load --source_format=CSV --replace --skip_leading_rows=1 raw_zone2.ScrapReason gs://bk_sqlserver_ahg/tablas/ScrapReason.csv schemas/ScrapReason.json
bq load --source_format=CSV --replace --skip_leading_rows=1 raw_zone2.Shift gs://bk_sqlserver_ahg/tablas/Shift.csv schemas/Shift.json
bq load --source_format=CSV --replace --skip_leading_rows=1 raw_zone2.ShipMethod gs://bk_sqlserver_ahg/tablas/ShipMethod.csv schemas/ShipMethod.json
bq load --source_format=CSV --replace --skip_leading_rows=1 raw_zone2.ShoppingCartItem gs://bk_sqlserver_ahg/tablas/ShoppingCartItem.csv schemas/ShoppingCartItem.json
bq load --source_format=CSV --replace --skip_leading_rows=1 raw_zone2.SpecialOffer gs://bk_sqlserver_ahg/tablas/SpecialOffer.csv schemas/SpecialOffer.json
bq load --source_format=CSV --replace --skip_leading_rows=1 raw_zone2.SpecialOfferProduct gs://bk_sqlserver_ahg/tablas/SpecialOfferProduct.csv schemas/SpecialOfferProduct.json
bq load --source_format=CSV --replace --skip_leading_rows=1 raw_zone2.StateProvince gs://bk_sqlserver_ahg/tablas/StateProvince.csv schemas/StateProvince.json
bq load --source_format=CSV --replace --skip_leading_rows=1 raw_zone2.Store gs://bk_sqlserver_ahg/tablas/Store.csv schemas/Store.json
bq load --source_format=CSV --replace --skip_leading_rows=1 raw_zone2.TransactionHistory gs://bk_sqlserver_ahg/tablas/TransactionHistory.csv schemas/TransactionHistory.json
bq load --source_format=CSV --replace --skip_leading_rows=1 raw_zone2.TransactionHistoryArchive gs://bk_sqlserver_ahg/tablas/TransactionHistoryArchive.csv schemas/TransactionHistoryArchive.json
bq load --source_format=CSV --replace --skip_leading_rows=1 raw_zone2.UnitMeasure gs://bk_sqlserver_ahg/tablas/UnitMeasure.csv schemas/UnitMeasure.json
bq load --source_format=CSV --replace --skip_leading_rows=1 raw_zone2.Vendor gs://bk_sqlserver_ahg/tablas/Vendor.csv schemas/Vendor.json
bq load --source_format=CSV --replace --skip_leading_rows=1 raw_zone2.WorkOrder gs://bk_sqlserver_ahg/tablas/WorkOrder.csv schemas/WorkOrder.json
bq load --source_format=CSV --replace --skip_leading_rows=1 raw_zone2.WorkOrderRouting gs://bk_sqlserver_ahg/tablas/WorkOrderRouting.csv schemas/WorkOrderRouting.json